version: "3.8"

services:
  order-service:
    build: .
    ports:
      - "5007:5007"
    environment:
      - PORT=5007
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
    command: ["node", "Order.js"]

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
