name: byteme
services:
  # Base Ollama service without GPU (for Mac)
  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    profiles: ["default", "cpu"]

  # GPU-enabled Ollama (for Windows with NVIDIA)
  ollama-gpu:
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles: ["gpu"]

  kong:
    container_name: kong
    image: kong:3.9
    ports:
      - "8000:8000"  # Proxy port
      - "8001:8001"  # Admin API
      - "8002:8002"  # Kong Manager
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "postgres.yanservers.com"
      KONG_PG_PORT: "5432"
      KONG_PG_USER: "esduser"
      KONG_PG_PASSWORD: "esduser"
      KONG_PG_DATABASE: "kong"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_LISTEN: "0.0.0.0:8002"
      KONG_ADMIN_GUI_URL: "http://localhost:8002"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # frontend:
  #   container_name: frontend
  #   image: nothic/byteme-frontend:latest
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./secrets/.env

volumes:
  ollama_data: