name: byteme
services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]



  kong:
    container_name: kong
    image: kong:3.9
    ports:
      - "8000:8000"  # Proxy port (for your APIs)
      - "8001:8001"  # Admin API
      - "8002:8002"  # GUI (Kong Manager)
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/config/kong.yaml"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_LISTEN: "0.0.0.0:8002"
      KONG_ADMIN_GUI_URL: "http://localhost:8002"
    volumes:
      - ./kong/config:/config

volumes:
  ollama_data: 