_format_version: "3.0"
services:
  - name: ai-service
    url: http://ollama:11434
    routes:
      - name: ai-route
        paths: ["/ai"]
        methods: ["POST", "OPTIONS"]  # Add OPTIONS for preflight
    
    # CORS plugin configuration
    plugins:
      - name: cors
        config:
          origins: ["http://localhost:3000"]  # Your Next.js dev server
          methods: ["POST", "OPTIONS"]
          headers: ["Content-Type"]
          credentials: true
          max_age: 3600

  - name: components-service
    url: https://personal-0careuf6.outsystemscloud.com
    routes:
      - name: components-route
        paths: ["/components"]
    plugins:
      - name: request-transformer
        config:
          replace:
            uri: "/ByteMeComponentService/rest/ComponentAPI/AllComponents"